data(Adult)
data(Groceries)
help(Adult)
Adult=as(Adult,"matrix")
Groceries=as(Groceries,"matrix")
View(Groceries)
View(Adult)
rules=apriori(Adult,parameter = list(support=0.02,confidence=0.5))
ruleExplorer(rules)
rules1=apriori(Groceries,parameter = list(support=0.02,confidence=0.5))
ruleExplorer(rules1)
